### PR TITLE
atlas/schema: added concurrent_index support

### PR DESCRIPTION
**Pull request by giautm**

### CODE REVIEW

**Comment by rotemtam** [comment]
@giautm  any news on this?

**Comment by giautm** [comment]
> @giautm any news on this?

Honestly, I haven't found an easy way to write a test for this with the operator yet. That's remain of pending

**Comment by rotemtam** [comment]
Perhaps you can make assertions about the created `atlas.hcl` configuration, after all you don't need to test atlas itself

**Review by datdao — APPROVED** [review]

**Review by rotemtam — COMMENTED** [review]
Test please !

**Pull request merged**
